# Dockerfile.test
FROM python:3.11-slim

WORKDIR /app

# Copie des fichiers de dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Installation des dépendances de test
RUN pip install pytest mongomock

# Copie des sources et des tests
COPY app/ /app/src/
COPY tests/ /app/tests/

# Commande par défaut
CMD ["pytest", "/app/tests", "-v"]